### ISSUE TITLE
Reenabling Windows support

### ISSUE THREAD

**Issue by poulson** [elemental/Elemental#21]
The current obstacle to compiling Elemental on Windows platforms is the lack of pthreads support (which is currently required for the distributed symmetric tridiagonal eigensolver, PMRRR). However, @tkelman has informed me that winpthreads (http://mingw-w64.sourceforge.net/) is liberally licensed and can be used as a replacement. It should ideally be possible to package winpthreads with PMRRR in order to support Windows.

**Comment by poulson** [comment]
Re-enabling Windows support should now be much easier thanks to it now being possible to disable pthreads within PMRRR: https://github.com/elemental/Elemental/commit/afa1863aed03541a77f2d0f7cc31859337a6ea75

**Comment by tkelman** [comment]
I don't think pthreads is really the biggest problem here, it's MPI. Looking at MS-MPI's license, it appears to actually allow binary redistribution (subject to export restrictions, and requiring distributors and end users to agree to equally protective license terms, and not using a strong copyleft license on your own code), which is better than nothing. The installer download page refuses to work in Chrome, and I'm not sure how I would go about scripting it on AppVeyor or another service. I'll see if I can get cmake to recognize MS-MPI on a local build. It may be tricky to get working with GCC (MinGW-w64) since MS-MPI is only giving me static `.lib` libraries.

**Comment by jeffhammond** [comment]
I don't understand your issues with MPI on Windows.  You can link against the MS-MPI binary the same as any other MPI implementation that is only available in binary form.  The license is compatible with Elemental's.  It might not be compatible with arbitrary third-party code, but I don't see why we should wring our hands over that here.

If you have Windows, you have IE and thus you should be able to download the installer.  It isn't too surprising that some Microsoft websites only work in their browser, but it's a trivial problem to solve in this case.

In any case, Intel MPI also supports Windows, but you have to pay for it.  However, I think the redistribution license is more flexible (please verify).

**Comment by poulson** [comment]
For what it's worth, I spent a significant portion of my (increasingly limited) free time trying to compile Elemental on the Windows 10 Technical Preview. The short overview is that I couldn't get MPI_Reduce_scatter to link with MS-MPI  using Visual Studio through the command line (despite being pretty confident in my link command), MinGW appears to be fundamentally broken (bsdtar.exe appears to do absolutely nothing), and Cygwin would likely work but was taking an excessive amount of time.

I don't have access to Windows 8 but would assume that things would go much smoother (and Windows 10 should be released in July.)

**Comment by jeffhammond** [comment]
Can you give me details of your issue?  I know the MS-MPI folks...

**Comment by poulson** [comment]
@jeffhammond I installed the most recent MS-MPI SDKs and the binaries and then specified the appropriate variables for overriding CMake's FindMPI. From memory, I just needed to specify the environment variable ``MSMPI_INC`` for CMake as ``"C:\Program Files (x86)\Microsoft SDKs\MPI\Include"`` since ``MSMPI_BIN`` is automatically set by the MS MPI installers. CMake found the appropriate libraries, but the ``MPI_Reduce_scatter`` detection still failed (specifically due to the ``MPI_Reduce_scatter`` symbol not being found).

With that said, it might not be worth spending too much time debugging with the technical preview of Windows 10, as I have noticed some very strange behavior,  such as unzipping taking tens of minutes instead of what would usually be less than a second.

**Comment by anhvoms** [comment]
@poulson This is Anh. I'm a developer on the MS-MPI team. @jeffhammond pointed me to this thread. 
Can you paste me the error from cmake about failing to find MPI_Reduce_scatter? Does this application have fortran code or only C/C++? Are you using MS-MPI v6?

Thanks

**Comment by poulson** [comment]
Hi @anhvoms! I just rebooted into Windows and reran the following procedure (with MS MPI v5; I'm currently downloading v6 and will report back soon):

1. Execute C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
2. Set ``MSMPI_INC`` to ``"C:\Program Files (x86)\Microsoft SDKs\MPI\Include"`` and ``MSMPI_BIN`` to ``"C:\Program Files\Microsoft MPI\Bin\"``.
3. Run ``cmake ..`` from within a ``build/`` subdirectory of Elemental
4. See the output
`` -- Found MPI_C: C:/Program Files (x86)/Microsoft SDKs/MPI/lib/x86/msmpi.lib
-- Found MPI_CXX: C:/Program Files (x86)/Microsoft SDKs/MPI/lib/x86/msmpi.lib
-- Looking for MPI_Reduce_scatter
-- Looking for MPI_Reduce_scatter - not found
CMake Error at cmake/tests/MPI.cmake:18 (message):
  Could not find MPI_Reduce_scatter
Call Stack (most recent call first):
  CMakeLists.txt:264 (include)
``
with ``CMakeFiles/CMakeError.log`` containing the following at the bottom:
``ClCompile:

  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\CL.exe /c /I"C:\Program Files (x86)\Microsoft SDKs\MPI\include" /Zi /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D CHECK_FUNCTION_EXISTS=MPI_Reduce_scatter /D _DEBUG /D RESTRICT=restrict /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTryCompileExec3391263162.dir\Debug\\" /Fd"cmTryCompileExec3391263162.dir\Debug\vc140.pdb" /Gd /TC /analyze- /errorReport:queue "C:\Program Files (x86)\CMake\share\cmake-3.2\Modules\CheckFunctionExists.c"

  Microsoft (R) C/C++ Optimizing Compiler Version 19.00.22816 for x86

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /I"C:\Program Files (x86)\Microsoft SDKs\MPI\include" /Zi /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D CHECK_FUNCTION_EXISTS=MPI_Reduce_scatter /D _DEBUG /D RESTRICT=restrict /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTryCompileExec3391263162.dir\Debug\\" /Fd"cmTryCompileExec3391263162.dir\Debug\vc140.pdb" /Gd /TC /analyze- /errorReport:queue "C:\Program Files (x86)\CMake\share\cmake-3.2\Modules\CheckFunctionExists.c"

  

  CheckFunctionExists.c

Link:

  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\link.exe /ERRORREPORT:QUEUE /OUT:"C:\Users\Jack Poulson\Source\Repos\Elemental\build\CMakeFiles\CMakeTmp\Debug\cmTryCompileExec3391263162.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib "C:\Program Files (x86)\Microsoft SDKs\MPI\lib\x86\msmpi.lib" /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /Debug /PDB:"C:/Users/Jack Poulson/Source/Repos/Elemental/build/CMakeFiles/CMakeTmp/Debug/cmTryCompileExec3391263162.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/Jack Poulson/Source/Repos/Elemental/build/CMakeFiles/CMakeTmp/Debug/cmTryCompileExec3391263162.lib" /MACHINE:X86 /SAFESEH  /machine:X86 /debug cmTryCompileExec3391263162.dir\Debug\CheckFunctionExists.obj

CheckFunctionExists.obj : error LNK2019: unresolved external symbol _MPI_Reduce_scatter referenced in function _main [C:\Users\Jack Poulson\Source\Repos\Elemental\build\CMakeFiles\CMakeTmp\cmTryCompileExec3391263162.vcxproj]

C:\Users\Jack Poulson\Source\Repos\Elemental\build\CMakeFiles\CMakeTmp\Debug\cmTryCompileExec3391263162.exe : fatal error LNK1120: 1 unresolved externals [C:\Users\Jack Poulson\Source\Repos\Elemental\build\CMakeFiles\CMakeTmp\cmTryCompileExec3391263162.vcxproj]

Done Building Project "C:\Users\Jack Poulson\Source\Repos\Elemental\build\CMakeFiles\CMakeTmp\cmTryCompileExec3391263162.vcxproj" (default targets) -- FAILED.



Build FAILED.



"C:\Users\Jack Poulson\Source\Repos\Elemental\build\CMakeFiles\CMakeTmp\cmTryCompileExec3391263162.vcxproj" (default target) (1) ->

(Link target) -> 

  CheckFunctionExists.obj : error LNK2019: unresolved external symbol _MPI_Reduce_scatter referenced in function _main [C:\Users\Jack Poulson\Source\Repos\Elemental\build\CMakeFiles\CMakeTmp\cmTryCompileExec3391263162.vcxproj]

  C:\Users\Jack Poulson\Source\Repos\Elemental\build\CMakeFiles\CMakeTmp\Debug\cmTryCompileExec3391263162.exe : fatal error LNK1120: 1 unresolved externals [C:\Users\Jack Poulson\Source\Repos\Elemental\build\CMakeFiles\CMakeTmp\cmTryCompileExec3391263162.vcxproj]



    0 Warning(s)

    2 Error(s)



Time Elapsed 00:00:00.59``

**Comment by poulson** [comment]
As an update, I see effectively the same output and errors after uninstalling MS MPI v5 and installing MS MPI v6.

**Comment by anhvoms** [comment]
@poulson I've done some initial investigation and this looks like the problem with Cmake not handling x86 calling conventions properly in their CheckFunctionExists.c file (CHECK_FUNCTION_EXISTS module). For x86 MS-MPI uses the __stdcall calling convention and thus the symbol for MPI_Reduce_scatter would look something like _MPI_Reduce_scatter@24 instead of _MPI_Reduce_scatter for cdecl (if you call dumpbin /exports on the x86 msmpi.lib you should see this). Cmake relies on cdecl because they're declaring the function in CheckFunctionExists.c as follows

#ifdef CHECK_FUNCTION_EXISTS

char CHECK_FUNCTION_EXISTS();
....

The best workaround is to skip the module CHECK_FUNCTION_EXISTS since this module cannot handle __stdcall. Normal compilation/linking should work because the prototypes in our mpi.h include the right calling convention.

Note that this problem should happen with any MPI functions and not with just MPI_Reduce_scatter. I have not looked at the source of Elemental (or at least the CMake config files for Elemental) so I'm unsure why MPI_Reduce_scatter was picked.

**Comment by poulson** [comment]
Thanks for the insight @anhvoms ! I think an even better workaround is to make use of ``check_c_source_compiles`` instead of ``check_function_exists``. I've taken a small step in this direction which I'll test here: https://github.com/elemental/Elemental/commit/565c393b7b277e953fa4ec0d340f0aa0c47e13cb

Should that lead to successful ``MPI_Reduce_scatter`` detection (which, to answer your question, I picked arbitrarily), I'll propagate it throughout the rest of Elemental's MPI tests.

**Comment by anhvoms** [comment]
Excellent! Glad it is working out.

**Comment by tkelman** [comment]
> MinGW appears to be fundamentally broken (bsdtar.exe appears to do absolutely nothing)

Which implementation / where did you get it from? If you were trying to use 32-bit mingw.org, that's obsolete and deprecated and should just go away - I've used bsdtar just fine in mingw-w64.

> I don't understand your issues with MPI on Windows.

I'm thinking about this in the context of trying to make Elemental, and MPI-using code more broadly, available via Julia bindings (or whatever other high-level language you like) in a way that would be easy to use for people who don't have Visual Studio installed, and more broadly aren't comfortable compiling large C++ codebases from source - but would appreciate the performance benefits of being able to use them.

We try to provide precompiled binaries that just get downloaded automatically when a user does `Pkg.add("Elemental")`, and you'd probably want to do the same thing via conda for Python bindings. For a single library like Elemental, most likely it'll be possible for @poulson to manually compile binaries himself upon new releases. This doesn't really scale beyond one library without automating the build process, and when you can't easily script the installation of MS-MPI or cross-compile from source leveraging a Linux package manager to do the hard work of dependency management (this is what we do for a large number of other binary packages in Julia), automation is much harder.

Keeping the build working with an often-quirky and nonconforming compiler like MSVC would also be much more tractable if we can integrate a continuous integration service like AppVeyor (essentially equivalent to Travis-CI, but for Windows) to test on every commit. A high level of scripting and automation is necessary to make this feasible.

**Comment by jeffhammond** [comment]
@tkelman That makes sense.  I forget get that there are people that want to do computational science without building from from source :-)

**Comment by anhvoms** [comment]
@tkelman 
You can automate the installation of MS-MPI by using
MSMPISetup.exe -unattend -force. Although the issue would be that if you are running within a script the environment variables MSMPI_BIN and MSMPI_INC would not be visible after the installation (you will need a new console for that to work)

**Comment by tkelman** [comment]
@anhvoms thanks, environment variables aren't too hard to handle in scripts. What I'm not as sure about would be getting the installer exe onto an unattended remote VM in the first place. I don't see a simple static URL from the download site that I could use powershell/curl to grab it from. I could repost the copy I just downloaded somewhere, dropbox or what have you, if that's kosher according to the license?

**Comment by anhvoms** [comment]
@tkelman You can get the direct download link by clicking on Download, ignoring the automatic download, and then clicking on "If your download does not start after 30 seconds, Click here". You should then see the direct download links for the MS-MPI SDK and the msmpisetup.exe

I've pasted them here for your convenience:
http://download.microsoft.com/download/6/4/A/64A7852A-A8C3-476D-908C-30501F761DF3/msmpisdk.msi

http://download.microsoft.com/download/6/4/A/64A7852A-A8C3-476D-908C-30501F761DF3/MSMpiSetup.exe

The license should also allow you to redistribute the binary and/or the installer so you can pre-download it and throw it on any downloadable storage place (e.g., dropbox)

**Comment by poulson** [comment]
I'm giving a talk any minute now, but I just committed a changeset which propagates ``check_c_source_compiles`` through the MPI tests: https://github.com/elemental/Elemental/commit/0555bc8183d38c959759b1d9d037a64051235688

**Comment by tkelman** [comment]
@jeffhammond
> I forget that there are people that want to do computational science without building from from source :-)

I don't mind compiling from source, but I like when the 15 people in my lab can easily use my code without having to.

@anhvoms perfect, I could have sworn I tried that a few days ago but must've tried the wrong link.

I'm past FindMPI now on my machine via `-DMPI_C_LIBRARIES="C:/Program Files (x86)/Microsoft SDKs/MPI/Lib/x86/msmpi.lib" -DMPI_C_INCLUDE_PATH="C:/Program Files (x86)/Microsoft SDKs/MPI/Include"`, will keep fiddling to get MATH_LIBS to work with one of my copies of openblas I have lying around.

**Comment by poulson** [comment]
@tkelman I have been pushing a massive amount of changes to Elemental, PMRRR, METIS, and ParMETIS to continue the bulldoze towards compiling Elemental on Windows. It's slow but steady.

**Comment by tkelman** [comment]
Awesome, that is extremely encouraging. I just pulled master and still no luck linking to openblas from MSVC, or to MS-MPI from MinGW-w64, but will hopefully get there.

**Comment by poulson** [comment]
@tkelman @anhvoms I have been busy adding DLL export interfaces to my ParMETIS clone, as well as PMRRR and Elemental (there is still work to be done), and the CMake+NMake build (using reference BLAS/LAPACK) now proceeds far enough for Elemental to hit what appears to be a bug in the VS 2015 pre-release. In particular, it appears that VS 2015 does not accept Elemental's usage of the ``constexpr`` function ``Collect<U>()`` to map a distribution tag to its AllGather'd tag within the following file:
    https://github.com/elemental/Elemental/blob/6145f9e64e37b4a0ea9f0294ceceb586e54f5d81/src/blas_like/level1/Copy/AllGather.cpp

**Comment by poulson** [comment]
@tkelman @anhvoms There is now an easily-reproduced example in ``compiler_bugs/MSVC/constexpr`` which breaks my pre-release of VS15: https://github.com/elemental/Elemental/blob/dfc797978467139e3e26ec0fb3e1d0b4f6b55437/compiler_bugs/MSVC/constexpr/constexpr.cpp

In order to easily build the example, move into said folder, create and move into a ``build/`` subfolder, and then run (from the Visual Studio Developer Command Prompt:

    cmake -G "NMake Makefiles" ..
    nmake VERBOSE=1

By default, the ``USE_CONSTEXPR`` CMake option is enabled, but you will see that, if it is disabled, then the example is built without the use of constexpr. You can do so by instead typing:

    cmake -G "NMake Makefiles" -D USE_CONSTEXPR=OFF ..
    nmake VERBOSE=1

**Comment by tkelman** [comment]
> using reference BLAS/LAPACK

Are you using some f2c version of these, or an ifort- or gfortran-built dll from somewhere?

I don't have MSVC 2015 or enough free disk space to try it on my local machine, though it's available on AppVeyor if we start testing there. On MSVC 2013 locally I see
```
-- Checking C++ support for "constexpr"
-- Checking C++ support for "constexpr": not supported
```
(and still having trouble linking to openblas)

Good idea for either you or @anhvoms to report the compiler bug, might be higher priority if it came from internally?

I have a retreat for the next few days but I'll look and see if MS-MPI can be made to link with MinGW - the errors so far looked pretty simple, using the `__int64` Microsoft extension. Feature request for @anhvoms, would be great to get some feature-checking into future versions of the MS-MPI headers, especially as newer MSVC is getting better about its C99 compliance which alleviates the need for many workarounds like `__int64`.

**Comment by poulson** [comment]
@tkelman For now, I'm simply downloading the reference implementations in the DLL's linked here: http://icl.cs.utk.edu/lapack-for-windows/lapack/index.html

And I am also a bit worried about C99 support since I assumed C99 in creating Elemental's C interface (which is the intermediary for running Elemental from Python and/or Julia). Hopefully not too many workarounds will be required. (So far, I believe that the largest workaround will be in marking the visibility of different symbols so that Windows builds proper ".lib"s for the shared libraries rather than just ".dll"s)

**Comment by tkelman** [comment]
Julia doesn't need .lib files, not as sure about Python. If you can use MSVC 2013 or 2015 then most C99 things are okay, with a few exceptions like VLA's and C99 complex numbers (both of which I think are now optional in C11?). For Python 2.7 you're stuck needing a very old MSVC 2008 where C99 support is almost nonexistent. There might be some ways of getting around this depending on how the bindings are structured, I think if it's the more modern ctypes/cffi style interface then you're not as constrained.

Julia will need to the appropriate symbols to be exported from the elemental dll however, so that might require some patching. Or you can manually write a def file to avoid touching the source, which I was recently dealing with in autotools. Cmake should let you add a def file to the link command without too much trouble if you go that route.

**Comment by anhvoms** [comment]
@tkelman Thanks for the feedback about __int64. We'll look into it for future versions. However, it might not be as easy because of the requirements on our backwards compatibility

**Comment by anhvoms** [comment]
@tkelman Can you paste the error produced by mingw wrt to __int64? I thought mingw defined __int64 into long long so it should work (in most cases). I'm attending training this week and don't have access to an environment where I can try to build msmpi applications with mingw. Thanks

**Comment by tkelman** [comment]
See https://gist.github.com/cdbf9fdd2f02b90ba3ba

This was running in MSYS2, via
```
cmake .. -DMPI_C_LIBRARIES="C:/Program Files (x86)/Microsoft SDKs/MPI/Lib/x86/msmpi.lib" -DMPI_C_INCLUDE_PATH="C:/Program Files (x86)/Microsoft SDKs/MPI/Include" -DMATH_LIBS="D:/code/Julia-0.3.0-0902-win32/bin/libopenblas.dll" -G"MSYS Makefiles"
```

It might be that `__int64` needs an include with mingw but is implicitly defined with msvc?

**Comment by anhvoms** [comment]
@tkelman You might want to try including _mingw.h before mpi.h according to this website
http://sebastien-brisard.blogspot.com/2013/09/scientific-computing-under-windows-7_27.html

But I will report this problem and we'll see what we can do to address this.

**Comment by tkelman** [comment]
AFAIK that's an internal header, not usually meant to be manually included by user code. `inttypes.h` and virtually every other header in the mingw crt would include `_mingw.h` internally. Including `inttypes.h` in the MS-MPI headers wouldn't hurt MSVC compilation, right?

**Comment by anhvoms** [comment]
@tkelman We try to avoid including other include files in mpi.h since it has the potential to break existing customer's environment (who has been successful compiling without any other include files). inttypes.h will break MSVC 2010 and MSVC 2012 compilers I believe

**Comment by tkelman** [comment]
> who has been successful compiling without any other include files

Not with gcc apparently. I'd be surprised if clang implicitly defined `__int64` without an include (maybe in msvc compatibility mode?), but I'd have to check.

We could probably modify the cmake test program here in elemental to add the extra include there.

**Comment by anhvoms** [comment]
@tkelman Sorry for the unclear comment. What I meant is that we try to limit additional include files to avoid breaking existing customers (those who already built successfully)

**Comment by poulson** [comment]
@tkelman @anhvoms I've submitted a bug report for the VS2015 issue: https://social.msdn.microsoft.com/Forums/en-US/7f209a6b-31f5-41d9-a589-e2b57fa53882/compilation-error-with-constexpr-template-declarations-in-vs2015?forum=visualstudiogeneral

**Comment by poulson** [comment]
FWIW, it would be okay to disable building PMRRR on Windows if necessary since there is a reasonable Divide and Conquer alternative (though it uses more memory and likely runs slightly slower, but is likely slightly more accurate).

**Comment by jeffhammond** [comment]
Can someone point me to the details of why PMRRR won't build on Windows?  I am having trouble finding them.

Is it Pthreads or C99 or something else?  I started hacking PMRRR to use atomics instead of Pthread locks yesterday and I guess I can convert it all the way to C++11 without too much effort.

**Comment by rhl-** [comment]
I just deleted the appveyor build unfortunately...

**Comment by poulson** [comment]
My memory was rusty. I extended PMRRR to support building without pthreads. The problem is DLL exports for dependencies like METIS.

**Comment by jeffhammond** [comment]
@poulson Thanks.  I am not going to touch METIS but was happy to do whatever it takes to make PMRRR more portable.  I will pursue the atomics route anyways but will wait on converting it to C++11 unless @pauldj finds it valuable enough to do but not valuable enough to do in his group.
